# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: FaizanAshiq.Tinysnap
PackageVersion: 1.2.0
InstallerType: exe
Scope: user
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/FaizanAshiq/tinysnap/releases/download/v1.2.0/Tinysnap-win-x64-Setup.exe
    InstallerSha256: 84D32ABF82EA8A8C291E6E0C7DB3FF83127DBC673D3FF67F7F198D21FFFA1B68
  - Architecture: arm64
    InstallerUrl: https://github.com/FaizanAshiq/tinysnap/releases/download/v1.2.0/Tinysnap-win-arm64-Setup.exe
    InstallerSha256: FC4BF60A265DEB685FF1EA1B900FD229D796AA0DCFB8932DF2D396351B91C05B
ManifestType: installer
ManifestVersion: 1.12.0
